export const UPDATE_POSTS = "UPDATE_POSTS";
export const SET_LOADING = "SET_LOADING";

//LOGIN ACTION TYPES;
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//SIGN UP ACTIONS

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const RESET_SIGNUP = "RESET_SIGNUP";

//ACTIONS FOR ADDING POST
export const ADD_POST = "ADD_POST";
export const ADD_POSTS = "ADD_POSTS";

//ACTIONS FOR TOGGLING LIKE
export const TOGGLE_LIKE = "TOGGLE_LIKE";
