POST http://localhost:1337/api/v1/comment/create HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MGExNmJkMDRkYmJiOTNlNTUzMGM1MDMiLCJmaXJzdE5hbWUiOiJTYW5za2FyIiwibGFzdE5hbWUiOiJCYW5zYWwiLCJ1c2VybmFtZSI6InNhbnNrYXJiYW5zYWwiLCJwYXNzd29yZCI6ImJsYWhibGFoYmxhaCIsIm1vYmlsZU51bWJlciI6ODA1OTk3NjYyOSwiZW1haWwiOiJzYW5za2FyYmFuc2FsNzVAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMS0wNS0xNlQxOTowMDozMi43ODdaIiwidXBkYXRlZEF0IjoiMjAyMS0wNS0xNlQxOTowMDozMi43ODdaIiwiX192IjowfQ.1doxWlUDt5SP2EuZl57go7kPS2V5msCJW6ZHBXKTbVY

{
    "postId": "60a1763a58b58040888a769f",
    "body": "This is my second comment."
}

#####
POST http://localhost:1337/api/v1/comment/get HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MGExNmJkMDRkYmJiOTNlNTUzMGM1MDMiLCJmaXJzdE5hbWUiOiJTYW5za2FyIiwibGFzdE5hbWUiOiJCYW5zYWwiLCJ1c2VybmFtZSI6InNhbnNrYXJiYW5zYWwiLCJwYXNzd29yZCI6ImJsYWhibGFoYmxhaCIsIm1vYmlsZU51bWJlciI6ODA1OTk3NjYyOSwiZW1haWwiOiJzYW5za2FyYmFuc2FsNzVAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMS0wNS0xNlQxOTowMDozMi43ODdaIiwidXBkYXRlZEF0IjoiMjAyMS0wNS0xNlQxOTowMDozMi43ODdaIiwiX192IjowfQ.1doxWlUDt5SP2EuZl57go7kPS2V5msCJW6ZHBXKTbVY
Content-Type: application/json

{
    "postId": "60a17830b82d4d40e6b14ff8"
}

###
POST http://localhost:1337/api/v1/comment/delete HTTP/1.1
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI2MGExNmJkMDRkYmJiOTNlNTUzMGM1MDMiLCJmaXJzdE5hbWUiOiJTYW5za2FyIiwibGFzdE5hbWUiOiJCYW5zYWwiLCJ1c2VybmFtZSI6InNhbnNrYXJiYW5zYWwiLCJwYXNzd29yZCI6ImJsYWhibGFoYmxhaCIsIm1vYmlsZU51bWJlciI6ODA1OTk3NjYyOSwiZW1haWwiOiJzYW5za2FyYmFuc2FsNzVAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMS0wNS0xNlQxOTowMDozMi43ODdaIiwidXBkYXRlZEF0IjoiMjAyMS0wNS0xNlQxOTowMDozMi43ODdaIiwiX192IjowfQ.1doxWlUDt5SP2EuZl57go7kPS2V5msCJW6ZHBXKTbVY

{
    "cId": "60a17ae20b2e87422e83b270"
}
