export const UPDATE_POSTS = "UPDATE_POSTS";
export const SET_LOADING = "SET_LOADING";

//LOGIN ACTION TYPES;
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//SIGN UP ACTIONS
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const RESET_SIGNUP = "RESET_SIGNUP";

//LOGOUT ACTIONS
export const LOGOUT_USER = "LOGOUT_USER";

//ACTIONS FOR  POST
export const ADD_POST = "ADD_POST";
export const ADD_POSTS = "ADD_POSTS";
export const DELETE_POST = "DELETE_POST";

//ACTIONS FOR COMMENTS

export const ADD_COMMENT = "ADD_COMMENT";

//ACTIONS FOR TOGGLING LIKE
export const TOGGLE_LIKE = "TOGGLE_LIKE";

//ACTIONS FOR SEARCHING USERS
export const START_SEARCH = "START_SEARCH";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
